### ISSUE TITLE
Imagen de perfil y buscador

### ISSUE THREAD

**Issue by sherrero96** [UNIZAR-30226-2018-05/Web#5]
Dos fallos que he visto:

1. En los requisitos no pone que un Usuario tenga una imagen de perfil. Por lo tanto, ni la API ni el Modelo ofrecen métodos para conseguir dicha imagen. En la web NO debería de aparecer.

2. El buscador, al darle al campo de Escritura,  se sube a la zona superior. Deberíamos de mirarlo.

**Comment by JorgeBlazHer** [comment]
Lo de la foto no sabía, lo quito. Respecto a lo de la barra de búsqueda, creo que es un bug de materialize, no he sabido como arreglarlo.
